# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code Parts
email: 
description: > # this means to ignore newlines until "baseurl:"
  A blog about web development, to share code and proof of concept projects with friends and workmates.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://code.parts" # the base hostname & protocol for your site
github_repository: paucasas/codeparts
permalink: pretty
excerpt_separator: "<!--more-->"
sass:
  style: compressed

# Build settings
markdown: kramdown
port: 4001